server:
  port: 9090
info:
  app:
    name: Boot-Actuator-App
    description: This is to learn actuators
    version: 1.0
    developer: Ashok
    email: ashokitschool@gmail.com
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans
  endpoint:
    shutdown:
      enabled: true